### ISSUE TITLE
Action automatically pushes latest tag if argument is omitted

### ISSUE THREAD

**Issue by EndBug** [Actions-R-Us/actions-tagger#19]
Even though the default value of `publish_latest` should be false the action still pushes the latest tag if you don't write anything.
Example workflow: https://github.com/EndBug/latest-tag/actions/runs/52295511/workflow
Workflow run: https://github.com/EndBug/latest-tag/runs/495238729?check_suite_focus=true#step:2:8

**Comment by smac89** [comment]
Very interesting. I will look into this

**Comment by smac89** [comment]
@EndBug fixed in latest version (`v1`)
