### ISSUE TITLE
Switch to major-version branch instead of tag?

### ISSUE THREAD

**Issue by jasonkarns** [Actions-R-Us/actions-tagger#20]
Git tags are not supposed to move. Any chance this action could be updated to push a `vN` major-version _branch_ on each release instead of force-overwriting tags?

**Comment by smac89** [comment]
I believe we can do this, but we don't have to drop support for tags because I prefer using tags for this kind of thing.

What I can do is to have a required flag which is used to indicate what kind of ref to create for the `vN` releases: either tag or branch.

**Comment by smac89** [comment]
See v2. This is now a configurable option
