### ISSUE TITLE
Don't run on prerelease

### ISSUE THREAD

**Issue by andstor** [Actions-R-Us/actions-tagger#23]
Currently, the action only detects if it is run in a release context. Adding an additional detection for checking if the release is a prerelease would make the release process more secure. Maybe also add a flag for bypassing this prerelease check?

Preferably, this should be solved by selecting the appropriate event in the workflow using this action. However, to my understanding, GitHub has no event that is emitted only by a "production" release. That is, not a prerelease. Therefore, when a release is published as a prerelease, triggering the `release > published` event, this action runs successfully. Updating major versions to a **prerelease** is not good. The only solution to this at the workflow level, seems to be to add a check in the workflow, stating: `if: "!github.event.release.prerelease"`. See [this](https://github.community/t5/GitHub-Actions/Release-Prerelease-action-triggers/m-p/42164/highlight/true#M4884).

So, solving this at the action level seems to be the most appropriate.

**Comment by smac89** [comment]
It is possible to solve this at the action level because we have access to [the prerelease flag](https://developer.github.com/v3/activity/events/types/#webhook-payload-example-32) in the payload.
I can add this fix.
In `v2` we can add a flag if developers want to bypass this behaviour

**Comment by andstor** [comment]
Great!

**Comment by smac89** [comment]
Ended up not adding a flag. However, v2 can check for edited releases and promote the tags if needed
