### ISSUE TITLE
ref_name output incorrect

### ISSUE THREAD

**Issue by namoscato** [Actions-R-Us/actions-tagger#43]
The documentation and metadata configuration specifies a `ref_name` output, but it seems `ref` is being set in the source code:

https://github.com/Actions-R-Us/actions-tagger/blob/d6cd6e9a848a64ea69a172b543ae1a0e54d86d48/src/action.ts#L48

**Comment by smac89** [comment]
You are quite right.
Fixed in latest release [v2](https://github.com/Actions-R-Us/actions-tagger/releases/tag/v2.0.1) release

**Comment by namoscato** [comment]
Thanks, @smac89!
