### ISSUE TITLE
Error: Reference cannot be updated

### ISSUE THREAD

**Issue by qrkourier** [Actions-R-Us/actions-tagger#87]
I'm investigating why v2 of this action failed with error:

> Error: Reference cannot be updated

run: https://github.com/openziti/ziti-builder/actions/runs/7007891069/job/19062989148

**Comment by smac89** [comment]
I did try to create a new release recently, but later, they were unpublished. I wonder if github didn't update the references 🤔. 

I will take a look later today.

**Comment by qrkourier** [comment]
I triggered another release and it didn't have this issue. I reduced my release activity type triggers from `["published", "edited"]` because I suspect it was caused by a race between both runs being triggered simultaneously when the draft release was edited in order to publish it.
